module.exports = {
  content: ['./resources/**/*.vue'],
  corePlugins: {
    flex: false,
    flexBasis: false,
    flexDirection: false,
    flexGrow: false,
    flexShrink: false,
    flexWrap: false,
    justifyContent: false,
    justifySelf: false,
    justifyItems: false,
    width: false,
    fill: false,
    fontFamily: false,
    height: false,
    maxWidth: false,
    maxHeight: false,
    padding: false,
    margin: false,
  },
  darkMode: 'class',
  theme: {},
  plugins: [],
};
